---
title: "Project, Package and Application Summary"
author: "Alexandre Momeni, Sacha Izadi, Amir Benmahjoub"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

##Project Summary

The wifiparis project was undertaken by Amir Benmahjoub, Sacha Izadi and Alexandre Momeni for their R course at École Polytechnique. It originated from a ParisData dataset on free public wifi hotspot connexions in 2016. This dataset was subsequently cleaned and structured to form part of a new R package called "wifiparis" and implemented into a Shiny App. The objective of the project is to enable end users to explore the dataset freely and gather insights through different visualisations in this App. (Please note that the maximum authorized duration length is limited to 2 hours i.e. 7200 seconds)

##Package Summary
##Data Cleaning and Structuring

The data cleaning consisted of  manipulations on the original dataset to render the data usable and interpretable.The data structuring consisted of creating several mapping files which enabled data labelling (language, category sites, devices, country region). 
For a more detailed overview, please see Data_Cleaning_Steps.R file in the data-raw folder.  

These datasets along with an additional spatial data which reflects individual sites and boroughs, form the data folder of the package. 

##Filters and Functions

The functions of the package were built to:
1) filter the relevant data the user selects in the Shiny App
2) create visualualisations with multiple levels of analysis

In particular, there are three visualisations: 

a) A leaflet map which provides geographical insights to the user. There are multiples layering options - clustering, coverage zones, arrondissement delimitations as well as individual information on sites through pop ups. The coverage zones corresponds to a radius of 100m around the wifi site.    

b) A treemap which provides insights on averagn number of connexions and duration for a given Axis of Analysis corresponding to size and colour inte sity respectively. The treemap also has a hierchachy view (axis of analysis: Ardt, Country of origin and the site's category) that allows the user to deepdive into geographical levels.  

c) Two types of the trend lines - one using the raw data and one with smoothered data - providing insights on the number of connexions for a given Axis of Analysis. These consider the timescope selected - the visualitation will plot either daily or hourly connections. 


##Shiny Application 

The Shiny Application provides a sidebar and a dashboard. 

In addition to the filters, the sidebar contains a link to the source code as well as a link to the filtered data with an option to download as a CSV file. 

The dashboard has the three visualisations from the R package. 


